#!/bin/bash
# open /Applications/X-Plane\ 12/X-Plane.app
# open /Users/fdup/Library/Application\ Support/Steam/steamapps/common/X-Plane\ 11/X-Plane.app
open /Users/fdup/Desktop/X-Plane\ 11.app
sleep 30
cd ~/VerifAI_XPlane_Project/scripts
python3 verifai_interface.py

